In [ ]:
import pandas as pd  #importing pandas library
data=pd.read_csv("student_lifestyle_dataset.csv") #load dataset
data.head() #display first 5 rows of the dataset


Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
0           1                  6.9                            3.8   
1           2                  5.3                            3.5   
2           3                  5.1                            3.9   
3           4                  6.5                            2.1   
4           5                  8.1                            0.6   

   Sleep_Hours_Per_Day  Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day  \
0                  8.7                   2.8                              1.8   
1                  8.0                   4.2                              3.0   
2                  9.2                   1.2                              4.6   
3                  7.2                   1.7                              6.5   
4                  6.5                   2.2                              6.6   

    GPA Stress_Level  
0  2.99     Moderate  
1  2.75          Low  
2  2.67          Low  
3  2.88     Moderate  
4  3.51         High

In [ ]:
data.shape #(rows,columns)

(2000, 8)

In [ ]:
data.describe() #statistical summary

Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
count  2000.000000          2000.000000                    2000.000000   
mean   1000.500000             7.475800                       1.990100   
std     577.494589             1.423888                       1.155855   
min       1.000000             5.000000                       0.000000   
25%     500.750000             6.300000                       1.000000   
50%    1000.500000             7.400000                       2.000000   
75%    1500.250000             8.700000                       3.000000   
max    2000.000000            10.000000                       4.000000   

       Sleep_Hours_Per_Day  Social_Hours_Per_Day  \
count          2000.000000           2000.000000   
mean              7.501250              2.704550   
std               1.460949              1.688514   
min               5.000000              0.000000   
25%               6.200000              1.200000   
50%               7.500000              2.600000   
75%               8.800000              4.100000   
max              10.000000              6.000000   

       Physical_Activity_Hours_Per_Day          GPA  
count                       2000.00000  2000.000000  
mean                           4.32830     3.115960  
std                            2.51411     0.298674  
min                            0.00000     2.240000  
25%                            2.40000     2.900000  
50%                            4.10000     3.110000  
75%                            6.10000     3.330000  
max                           13.00000     4.000000

In [ ]:
data.info() #information about dataset - more about columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Student_ID                       2000 non-null   int64  
 1   Study_Hours_Per_Day              2000 non-null   float64
 2   Extracurricular_Hours_Per_Day    2000 non-null   float64
 3   Sleep_Hours_Per_Day              2000 non-null   float64
 4   Social_Hours_Per_Day             2000 non-null   float64
 5   Physical_Activity_Hours_Per_Day  2000 non-null   float64
 6   GPA                              2000 non-null   float64
 7   Stress_Level                     2000 non-null   object 
dtypes: float64(6), int64(1), object(1)
memory usage: 125.1+ KB


In [ ]:
data.isnull().sum() #checking for missing values

Student_ID                         0
Study_Hours_Per_Day                0
Extracurricular_Hours_Per_Day      0
Sleep_Hours_Per_Day                0
Social_Hours_Per_Day               0
Physical_Activity_Hours_Per_Day    0
GPA                                0
Stress_Level                       0
dtype: int64

In [ ]:
data.duplicated().sum() #checking for duplicate rows

np.int64(0)

In [ ]:
data.drop(columns=["Student_ID"],axis=1) #dropping Student_ID column as it is not useful for prediction

Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  Sleep_Hours_Per_Day  \
0                     6.9                            3.8                  8.7   
1                     5.3                            3.5                  8.0   
2                     5.1                            3.9                  9.2   
3                     6.5                            2.1                  7.2   
4                     8.1                            0.6                  6.5   
...                   ...                            ...                  ...   
1995                  6.5                            0.2                  7.4   
1996                  6.3                            2.8                  8.8   
1997                  6.2                            0.0                  6.2   
1998                  8.1                            0.7                  7.6   
1999                  9.0                            1.7                  7.3   

      Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day   GPA Stress_Level  
0                      2.8                              1.8  2.99     Moderate  
1                      4.2                              3.0  2.75          Low  
2                      1.2                              4.6  2.67          Low  
3                      1.7                              6.5  2.88     Moderate  
4                      2.2                              6.6  3.51         High  
...                    ...                              ...   ...          ...  
1995                   2.1                              7.8  3.32     Moderate  
1996                   1.5                              4.6  2.65     Moderate  
1997                   0.8                             10.8  3.14     Moderate  
1998                   3.5                              4.1  3.04         High  
1999                   3.1                              2.9  3.58         High  

[2000 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder #Importing LabelEncoder from sklearn
label_encoder=LabelEncoder() #Creating object of LabelEncoder
data["Stress_Level"]=label_encoder.fit_transform(data["Stress_Level"]) #Encoding target column

In [13]:
data.head()

Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
0           1                  6.9                            3.8   
1           2                  5.3                            3.5   
2           3                  5.1                            3.9   
3           4                  6.5                            2.1   
4           5                  8.1                            0.6   

   Sleep_Hours_Per_Day  Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day  \
0                  8.7                   2.8                              1.8   
1                  8.0                   4.2                              3.0   
2                  9.2                   1.2                              4.6   
3                  7.2                   1.7                              6.5   
4                  6.5                   2.2                              6.6   

    GPA  Stress_Level  
0  2.99             2  
1  2.75             1  
2  2.67             1  
3  2.88             2  
4  3.51             0

In [14]:
x=data.drop(columns=["Stress_Level"],axis=1) #features
y=data["Stress_Level"] #target variable
from sklearn.model_selection import train_test_split #importing train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42) #splitting data into training and testing sets

In [16]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion="gini",max_depth=3) #Creating Decision Tree Classifier model
model.fit(x_train,y_train) #Training the model  

DecisionTreeClassifier(max_depth=3)

In [21]:
y_predict=model.predict(x_test) #Predicting on test data

In [26]:
result = label_encoder.inverse_transform(y_predict)
print("Prediction:", result[0:10])  #display first 10 predictions


Prediction: ['Moderate' 'Low' 'High' 'Moderate' 'High' 'Moderate' 'High' 'Moderate'
 'Moderate' 'High']


In [27]:
print("Y_test:", label_encoder.inverse_transform(y_test.values[0:10]))  #display first 10 actual values

Y_test: ['Moderate' 'Low' 'High' 'Moderate' 'High' 'Moderate' 'High' 'Moderate'
 'Moderate' 'High']


In [24]:
#compare the y_predict and y_test to evaluate model performance
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy=accuracy_score(y_test,y_predict)   #calculating accuracy
confusion=confusion_matrix(y_test,y_predict) #confusion matrix
report=classification_report(y_test,y_predict) #classification report
print("Accuracy:",accuracy)
print("Confusion Matrix:\n",confusion)
print("Classification Report:\n",report)
accuracy #display accu

Accuracy: 1.0
Confusion Matrix:
 [[206   0   0]
 [  0  67   0]
 [  0   0 127]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       206
           1       1.00      1.00      1.00        67
           2       1.00      1.00      1.00       127

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400



1.0

1.0